### ISSUE TITLE
yif_addict_dol_obj methods should have exceptions

### ISSUE THREAD

**Issue by keremkoseoglu** [keremkoseoglu/addict#3]

**Comment by rjbhayani** [comment]
Hi,

I am facing below issue while importing repository

![image](https://user-images.githubusercontent.com/19501487/125668143-98ebb358-d69e-4a9e-b0ed-48606017f904.png)

**Comment by keremkoseoglu** [comment]
@rjbhayani your language problem is handled under #15 .

**Comment by keremkoseoglu** [comment]
Inspected yif_addict_dol_obj methods. No exception class is needed. Closing.
