### ISSUE TITLE
master language not EN

### ISSUE THREAD

**Issue by tricktresor** [keremkoseoglu/addict#4]
The master language should be EN due to compatiblity.
Language TR causes an error at importing this repository even with "advanced - open in master language".
Maybe because language TR is not installed in our system?
Regards
Enno

**Comment by keremkoseoglu** [comment]
@tricktresor  I was able to import this package to other systems, but all had the language TR installed. 

Do you have the time to fork this repository, edit .abapgit.xml and change the master language to E, and install the forked repository via abapGit?

`<MASTER_LANGUAGE>E</MASTER_LANGUAGE>`

If that solves the problem, I will happily accept your pull request.

**Comment by tricktresor** [comment]
that was easy... ;)
thanks for your fast reposnse!
